user root;
worker_processes  1;

events {
}


http {
    client_max_body_size 30M;

    server {

        listen       80;
        server_name  localhost;
        charset utf-8;

        location / {
            proxy_pass http://frontend:3000/;
        }

        location /api/ {
            proxy_pass http://backend:8000/;
        }
        
        location /media/ {
            alias /app/media/;
            charset utf-8;
        }
    }
}