# Generated by Django 6.0.4 on 2026-05-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_users_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlCheckResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('probability', models.FloatField()),
            ],
        ),
    ]
