# Generated by Django 6.0.4 on 2026-05-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_urlcheckresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlcheckresults',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
