# Generated by Django 6.0.4 on 2026-05-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_review_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
