# Generated by Django 6.0.4 on 2026-05-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_urlcheckresults_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlcheckresults',
            name='user',
        ),
    ]
