# Generated by Django 6.0.4 on 2026-05-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_urlcheckresults_user_favorite'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_content_type_object_id',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
